### ISSUE TITLE
Auth cookie not sent with some initial requests

### ISSUE THREAD

**Issue by tstodter** [SharpNotions/pantry-list-frontend#43]
Early requests (maybe just the first) after logging in don't seem to send a Cookie header along to `/api/lists` or `/api/unranked_items`, resulting in a 401 Unauthorized.

**Comment by atomdmac** [comment]
The exact message returned from the `lists` endpoint is: `No auth found.`

**Comment by atomdmac** [comment]
Fixed by way of PR #51 .  Tested and verified on production.
